# Generated by Django 5.0.4 on 2024-06-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
